[pytest]
testpaths = tests
addopts = --alluredir=allure-results


;logger --> conf test

;allure report
;Run --> pytest 
; it will generate allure-results folder - add ini details
; download allure zip and add it to env variable -  https://github.com/allure-framework/allure2/releases/tag/2.45.0
; allure serve allure-results

;add before test method
; @allure.title("Invalid Login Test")
; @allure.description("Verify login fails with invalid credentials")

;add before page object
; @allure.step("Login with username: {username}")

;parallel
;pip install pytest-xdist
;pytest -n 2
;pytest -n 2 -m smoke


;npx playwright codegen
;explain playwright inspector 

;playwright cli
;npm install -g @playwright/cli@latest

;npx playwright show-trace login-trace.zip


; context.tracing.start(
;         screenshots=True,
;         snapshots=True,
;         sources=True
;     )

; context.tracing.stop(
;         path="traces/test_trace.zip"
;     )